// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2xiA0kgn90m0fcaL6SRblQq-xO10f-Pg',
    appId: '1:1069399548191:web:c5c642fc4c2e22e440102a',
    messagingSenderId: '1069399548191',
    projectId: 'task-d32c7',
    authDomain: 'task-d32c7.firebaseapp.com',
    storageBucket: 'task-d32c7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOo0_XyQqhVOqtWZlltPTygT4mYzYrE00',
    appId: '1:1069399548191:android:152442620ece6e4140102a',
    messagingSenderId: '1069399548191',
    projectId: 'task-d32c7',
    storageBucket: 'task-d32c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4a2ZFj5BKyFkpK3lZUXcvbx-IviPt4BI',
    appId: '1:1069399548191:ios:4709f2c2407dfeb740102a',
    messagingSenderId: '1069399548191',
    projectId: 'task-d32c7',
    storageBucket: 'task-d32c7.firebasestorage.app',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4a2ZFj5BKyFkpK3lZUXcvbx-IviPt4BI',
    appId: '1:1069399548191:ios:78fecb732d5799d140102a',
    messagingSenderId: '1069399548191',
    projectId: 'task-d32c7',
    storageBucket: 'task-d32c7.firebasestorage.app',
    iosBundleId: 'com.example.task.RunnerTests',
  );
}
